# -*- coding: utf-8 -*-
"""Rでt検定

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15dnVso6D8RjwMQDL736t0X2-SlxvAK2J
"""

# Rでt検定
# 10,20,30,40,50の数字を書き換えてください

x <- c(10, 20, 30, 40, 50)

# 40,50,60,70,80の数字を書き換えてください

y <- c(40, 50, 60, 70, 80)

# それぞれの平均と標準偏差を表示します

mean (x)
sd(x)
mean(y)
sd(y)

# t検定を行います

t.test(x, y)

# ATPの結果

x <- c(100, 100, 100, 100)
y <- c(83.8998, 81.7114, 87.3822, 85.3472)

# それぞれの平均と標準偏差を表示します

mean (x)
sd(x)
mean(y)
sd(y)

# t検定を行います
# p<0.01　なので有意差があります

t.test(x, y)